// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3VlCLw739cDbAA60B5UVnVUpzle51K8Y',
    appId: '1:728640036406:web:9d11c672c5744b342d4297',
    messagingSenderId: '728640036406',
    projectId: 'tiktok-31seul',
    authDomain: 'tiktok-31seul.firebaseapp.com',
    storageBucket: 'tiktok-31seul.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZR3b_65MvJ6le_NLvouw-TUW9hVq-l0',
    appId: '1:728640036406:android:194ab3d54553bcfc2d4297',
    messagingSenderId: '728640036406',
    projectId: 'tiktok-31seul',
    storageBucket: 'tiktok-31seul.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9AThIiH8uOoI03Vvjgn27giNN-eqPqQ',
    appId: '1:728640036406:ios:556a942fc9c9201e2d4297',
    messagingSenderId: '728640036406',
    projectId: 'tiktok-31seul',
    storageBucket: 'tiktok-31seul.appspot.com',
    iosClientId: '728640036406-fjfadtokatli0jjhln7lrpdub86n3dcb.apps.googleusercontent.com',
    iosBundleId: 'com.31seul.tiktokClone',
  );
}
